# Generated by Django 4.2.6 on 2024-02-26 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('associated_keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('document', models.FileField(upload_to='')),
                ('display_name', models.CharField(max_length=150)),
                ('document_format', models.CharField(max_length=12)),
                ('document_text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('orig_doc_date', models.DateField()),
                ('keyword', models.ManyToManyField(to='file_api.keyword')),
            ],
        ),
    ]
