# Generated by Django 4.2.6 on 2023-11-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('primary_filepath', models.CharField(max_length=300)),
                ('primary_format', models.CharField(max_length=12)),
                ('file_text', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('orig_doc_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_keyword', models.CharField(max_length=200)),
                ('file', models.ManyToManyField(to='file_api.file')),
            ],
        ),
    ]
