# Generated by Django 4.2.6 on 2024-03-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0003_file_upload_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='approval_timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-09 14:22:40.274306'),
            preserve_default=False,
        ),
    ]
