# Generated by Django 4.2.6 on 2023-11-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0003_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload',
            field=models.FileField(default='upload', upload_to=''),
            preserve_default=False,
        ),
    ]
