# Generated by Django 4.2.6 on 2024-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0004_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='primary_format',
            new_name='document_format',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='primary_filepath',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_text',
        ),
        migrations.AddField(
            model_name='file',
            name='document_text',
            field=models.TextField(default='no text available'),
            preserve_default=False,
        ),
    ]
