# Generated by Django 4.2.6 on 2024-03-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0004_file_approval_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
