# Generated by Django 4.2.6 on 2024-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0006_file_suggested_description_file_suggested_doc_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='suggested_description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='suggested_doc_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='suggested_doc_date_range_end',
        ),
        migrations.RemoveField(
            model_name='file',
            name='suggested_keyword',
        ),
        migrations.RemoveField(
            model_name='file',
            name='suggested_name',
        ),
        migrations.AddField(
            model_name='file',
            name='uploader_suggested_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader_suggested_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader_suggested_doc_date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader_suggested_keywords',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='uploader_suggested_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
